// Dados reais do cardápio da E Tenho Ditto Pizzaria
// Fonte: informações fornecidas pelo cliente (cardápio iFood)

const pizzaSizes = [
  {
    name: "Pizza Grande",
    slug: "grande",
    slices: 12,
    maxFlavors: 4,
    servesPeople: 4,
    price: 108.0,
    description:
      "Monte sua Pizza Grande com até 4 sabores - 12 fatias - 35cm. Obs: Todos sabores salgados levam mussarela, molho de tomate e orégano.",
    order: 1,
  },
  {
    name: "Pizza Média",
    slug: "media",
    slices: 9,
    maxFlavors: 3,
    servesPeople: 3,
    price: 95.0,
    description:
      "Monte sua Pizza Média com até 3 sabores - 9 fatias - 30cm. Obs: Todos sabores salgados levam mussarela, molho de tomate e orégano.",
    order: 2,
  },
  {
    name: "Pizza Pequena",
    slug: "pequena",
    slices: 6,
    maxFlavors: 2,
    servesPeople: 2,
    price: 85.0,
    description:
      "Monte sua Pizza Pequena com até 2 sabores - 6 fatias - 25cm. Obs: Todos sabores salgados levam mussarela, molho de tomate e orégano.",
    order: 3,
  },
];

const borders = [
  { name: "4 Queijos", price: 15.0, type: "SALGADA", order: 1 },
  { name: "Santa Massa", price: 15.0, type: "SALGADA", order: 2 },
  { name: "Catupiry", price: 15.0, type: "SALGADA", order: 3 },
  { name: "Cheddar", price: 12.0, type: "SALGADA", order: 4 },
  { name: "Chocolate Preto", price: 12.0, type: "DOCE", order: 5 },
  { name: "Chocolate Branco", price: 12.0, type: "DOCE", order: 6 },
  { name: "Chocolate Mesclado", price: 12.0, type: "DOCE", order: 7 },
];

// Sabores salgados
const salgados = [
  { name: "4 Queijos", description: "Mussarela, parmesão, provolone e Catupiry", extraPrice: 0 },
  { name: "5 Queijos", description: "Mussarela, parmesão, provolone, Catupiry e gorgonzola", extraPrice: 0 },
  { name: "6 Queijos", description: "Mussarela, parmesão, provolone, Catupiry, gorgonzola e cheddar", extraPrice: 0 },
  { name: "6 Queijos c/ Doritos", description: "Mussarela, parmesão, provolone, Catupiry, gorgonzola, cheddar e Doritos", extraPrice: 6 },
  { name: "Alho e Óleo", description: "Alho e azeite", extraPrice: 0 },
  { name: "Atum", description: "Atum ralado e cebola", extraPrice: 0 },
  { name: "Bacon", description: "Bacon crocante e Catupiry", extraPrice: 0 },
  { name: "Bacon com Abacaxi e Geleia de Pimenta", description: "Bacon, Catupiry, abacaxi assado e geleia especial", extraPrice: 7 },
  { name: "Bacon c/ Brócolis", description: "Brócolis, bacon, Catupiry e parmesão", extraPrice: 0 },
  { name: "Bacon c/ Cheddar", description: "Frango, bacon, cheddar e cebola", extraPrice: 0 },
  { name: "Bacon com Milho", description: "Bacon, milho e Catupiry", extraPrice: 0 },
  { name: "Bacon com Ovo", description: "Bacon crocante com ovos", extraPrice: 0 },
  { name: "Basca", description: "Bacon, tomate e Catupiry", extraPrice: 0 },
  { name: "Brócolis", description: "Brócolis e Catupiry", extraPrice: 0 },
  { name: "Calabresa", description: "Calabresa fatiada", extraPrice: 0 },
  { name: "Calabresa + Bacon", description: "Calabresa, bacon e ovo", extraPrice: 0 },
  { name: "Calabresa + Cheddar", description: "Calabresa, cheddar e cebola", extraPrice: 0 },
  { name: "Calabresa + Fritas", description: "Calabresa, fritas e cheddar", extraPrice: 7 },
  { name: "Calabresa Especial", description: "Calabresa, cebola e azeitona", extraPrice: 0 },
  { name: "Calabresa Mix", description: "Combinação de calabresa, coração, bacon e frango", extraPrice: 12 },
  { name: "Calabresa Picante", description: "Calabresa, cebola e molho de pimenta suave", extraPrice: 0 },
  { name: "Camarão", description: "Camarão e Catupiry", extraPrice: 17 },
  { name: "Camarão Especial", description: "Strogonoff de camarão", extraPrice: 17 },
  { name: "Copa Figo", description: "Copa, figo, cream cheese e mel", extraPrice: 10 },
  { name: "Coração", description: "Coração e Catupiry", extraPrice: 10 },
  { name: "Coração e Brócolis", description: "Brócolis, coração e Catupiry", extraPrice: 12 },
  { name: "Coração Santa Massa", description: "Coração ao creme de alho Santa Massa", extraPrice: 12 },
  { name: "Coração c/ Bacon", description: "Coração e bacon", extraPrice: 12 },
  { name: "Filé", description: "Iscas de carne e Catupiry (batata palha opcional)", extraPrice: 0 },
  { name: "Filé com Palha", description: "Iscas de carne e Catupiry com batata palha", extraPrice: 0 },
  { name: "Filé Barbecue", description: "Iscas de carne, molho barbecue e cebola roxa", extraPrice: 0 },
  { name: "Filé c/ Alho", description: "Iscas de carne e alho", extraPrice: 0 },
  { name: "Filé c/ Batata Rústica", description: "Filé com Catupiry e batatas rústicas", extraPrice: 10 },
  { name: "Filé c/ Calabresa e Bacon", description: "Iscas de carne, bacon e calabresa", extraPrice: 7 },
  { name: "Filé c/ Catupiry", description: "Iscas de carne, milho, gorgonzola, cebola, tomate e Catupiry", extraPrice: 0 },
  { name: "Filé c/ Cheddar", description: "Iscas de carne, tomate, pimentão, cebola e cheddar", extraPrice: 0 },
  { name: "Filé Crispy", description: "Iscas de filé, Catupiry e cebola crispy", extraPrice: 7 },
  { name: "Filé c/ Fritas e Creme de Alho", description: "Iscas de carne, Catupiry, creme de alho Santa Massa e fritas", extraPrice: 10 },
  { name: "Filé Gorgonzola", description: "Iscas de carne, Catupiry e gorgonzola", extraPrice: 0 },
  { name: "Filé com Milho", description: "Iscas de carne, tomate e milho", extraPrice: 0 },
  { name: "Filé c/ Queijo Coalho", description: "Iscas de carne, queijo coalho, cebola roxa e Catupiry", extraPrice: 12 },
  { name: "Filé Quatro Queijos", description: "Iscas de carne, mussarela, parmesão, provolone e Catupiry", extraPrice: 10 },
  { name: "Filé Molho de Nata", description: "Iscas de carne e molho de nata", extraPrice: 10 },
  { name: "Frango", description: "Frango desfiado com Catupiry", extraPrice: 0 },
  { name: "Frango c/ Batata Rústica", description: "Frango com Catupiry e batatas rústicas", extraPrice: 7 },
  { name: "Frango c/ Cheddar", description: "Frango, bacon, cheddar e cebola", extraPrice: 0 },
  { name: "Frango com Fritas", description: "Frango com Catupiry e batatas fritas", extraPrice: 7 },
  { name: "Fricassê", description: "Frango cremoso (batata palha opcional)", extraPrice: 0 },
  { name: "Fricassê com Palha", description: "Frango cremoso com batata palha", extraPrice: 0 },
  { name: "Italiana", description: "Salame italiano e Catupiry", extraPrice: 0 },
  { name: "Italianíssima", description: "Salame italiano, pimentão verde e molho de pimenta suave", extraPrice: 0 },
  { name: "Lombo", description: "Lombo canadense e Catupiry", extraPrice: 0 },
  { name: "Lombo + Bacon", description: "Lombo canadense, bacon e Catupiry", extraPrice: 0 },
  { name: "Lombo com Abacaxi", description: "Lombo canadense, abacaxi e Catupiry", extraPrice: 0 },
  { name: "Lombo c/ Queijo Coalho", description: "Lombo com queijo coalho e mel", extraPrice: 7 },
  { name: "Margherita", description: "Tomate, manjericão fresco e parmesão", extraPrice: 0 },
  { name: "Milho", description: "Milho e muito Catupiry", extraPrice: 0 },
  { name: "Mussarela", description: "Mussarela em dobro", extraPrice: 0 },
  { name: "Onion", description: "Iscas de carne, bacon, molho barbecue, cheddar e anéis de cebola fritos", extraPrice: 7 },
  { name: "Palmito", description: "Palmito e Catupiry", extraPrice: 0 },
  { name: "Peito de Peru", description: "Peito de peru, tomate cereja e manjericão", extraPrice: 0 },
  { name: "Pepperoni", description: "Calabresa pepperoni", extraPrice: 7 },
  { name: "Pepperoni Especial", description: "Pepperoni, abacaxi e gorgonzola", extraPrice: 7 },
  { name: "Philadelphia", description: "Salmão passado ao forno, geleia de pimenta e cebolinha", extraPrice: 12 },
  { name: "Philadelphia Ocidental", description: "Salmão cru, cream cheese, molho tarê e cebolinha", extraPrice: 12 },
  { name: "Picanha", description: "Suculentos pedaços de picanha", extraPrice: 10 },
  { name: "Picanha Mostarda e Mel", description: "Picanha e molho mostarda e mel da casa", extraPrice: 10 },
  { name: "Picanha Santa Massa", description: "Picanha ao creme de alho Santa Massa", extraPrice: 12 },
  { name: "Picanha 4 Queijos", description: "Picanha, mussarela, parmesão, provolone e Catupiry", extraPrice: 12 },
  { name: "Portuguesa", description: "Tomate, ovos, pimentão, presunto, azeitona e cebola", extraPrice: 0 },
  { name: "Ruffles", description: "Mussarela e Ruffles", extraPrice: 6 },
  { name: "Strogonoff de Carne", description: "Strogonoff de carne (opcional de batata palha)", extraPrice: 0 },
  { name: "Strogonoff de Carne com Palha", description: "Strogonoff de carne com batata palha", extraPrice: 0 },
  { name: "Tomate Seco", description: "Tomate seco e rúcula", extraPrice: 0 },
  { name: "Vegetariana", description: "Tomate, cebola, palmito, brócolis e milho", extraPrice: 0 },
];

// Sabores doces
const doces = [
  { name: "Chocolate Preto", description: "Chocolate preto", extraPrice: 0 },
  { name: "Chocolate Branco", description: "Chocolate branco", extraPrice: 0 },
  { name: "Chocolate Mesclado", description: "Chocolate mesclado branco e preto", extraPrice: 0 },
  { name: "Brigadeiro", description: "Chocolate preto, granulado e leite condensado", extraPrice: 0 },
  { name: "Califórnia", description: "Pêssego, abacaxi, figo, mussarela e leite condensado", extraPrice: 0 },
  { name: "Charge", description: "Chocolate preto, paçoca e leite condensado", extraPrice: 0 },
  { name: "Charge White", description: "Chocolate branco, paçoca e leite condensado", extraPrice: 0 },
  { name: "Prestígio", description: "Chocolate preto, coco e leite condensado", extraPrice: 0 },
  { name: "Prestígio White", description: "Chocolate branco, coco e leite condensado", extraPrice: 0 },
  { name: "Cheesecake de Morango", description: "Chocolate branco, cream cheese e geleia de morango", extraPrice: 7 },
  { name: "Chocolate Preto com Morango", description: "Chocolate preto e morangos", extraPrice: 10 },
  { name: "Chocolate Branco com Morango", description: "Chocolate branco e morangos", extraPrice: 10 },
  { name: "Chocolate Mesclado com Morango", description: "Chocolate preto e branco com morangos", extraPrice: 10 },
  { name: "Chocolate com Nozes", description: "Chocolate branco, nozes e leite condensado", extraPrice: 7 },
  { name: "Fondue", description: "Chocolate preto, morangos, uva e Nutella", extraPrice: 15 },
  { name: "Kinder Bueno", description: "Chocolate branco e creme Bueno", extraPrice: 15 },
  { name: "Kinder Bueno c/ Morango", description: "Chocolate branco, creme Bueno e morangos", extraPrice: 17 },
  { name: "Kitkat", description: "Chocolate e Kitkat", extraPrice: 7 },
  { name: "Kitkat White", description: "Chocolate branco e Kitkat White", extraPrice: 7 },
  { name: "M&M's", description: "Chocolate e M&M's", extraPrice: 7 },
  { name: "Nutella", description: "Nutella e nozes", extraPrice: 15 },
  { name: "Nutella c/ Morango", description: "Nutella, morango e leite Ninho", extraPrice: 17 },
  { name: "Ouro Branco", description: "Chocolate e bombons Ouro Branco", extraPrice: 7 },
  { name: "Raffaello", description: "Chocolate branco, coco e leite condensado", extraPrice: 15 },
  { name: "Raffaello c/ Morango", description: "Chocolate branco, coco, leite condensado e morangos", extraPrice: 17 },
  { name: "Raffaello Especial", description: "Chocolate branco, Raffaello, Kinder Bueno e morango", extraPrice: 23 },
  { name: "Stikadinho", description: "Chocolate e Stikadinho", extraPrice: 5 },
  { name: "Uva", description: "Chocolate branco, uva, Nutella e leite Ninho", extraPrice: 10 },
];

const flavors = [
  ...salgados.map((f, i) => ({ ...f, type: "SALGADA", order: i + 1 })),
  ...doces.map((f, i) => ({ ...f, type: "DOCE", order: i + 1 })),
];

// Produtos fixos: combos, pizza vulcão, e bebidas
const products = [
  {
    name: "Combo Pizza Grande + Brotinho",
    description:
      "Combo Família: 1 Pizza Grande (4 sabores - 12 fatias - 35cm) + 1 Pizza Broto por apenas R$ 29,90",
    price: 134.9,
    servesPeople: 4,
    category: "COMBO",
    order: 1,
  },
  {
    name: "Pizza Vulcão - Grande (até 3 sabores)",
    description:
      "E Tenho Ditto agora com pizza vulcão! Pizza Grande com até 3 sabores - 12 fatias - 35cm. Obs: tempo de preparo +15 min.",
    price: 142.0,
    servesPeople: 4,
    category: "ESPECIAL",
    order: 2,
  },
  { name: "Coca-Cola 2L", description: "Garrafa 2 litros", price: 16.5, category: "BEBIDA", order: 3 },
  { name: "Coca-Cola Zero 2L", description: "Garrafa 2 litros", price: 16.5, category: "BEBIDA", order: 4 },
  { name: "Fruki Guaraná 2L", description: "Garrafa 2 litros", price: 13.0, category: "BEBIDA", order: 5 },
  { name: "Fruki Guaraná Zero 2L", description: "Garrafa 2 litros", price: 13.0, category: "BEBIDA", order: 6 },
  { name: "Coca-Cola Original 600ml", description: "Garrafa 600ml", price: 9.0, category: "BEBIDA", order: 7 },
  { name: "Coca-Cola Zero 600ml", description: "Garrafa 600ml", price: 9.0, category: "BEBIDA", order: 8 },
  { name: "Refrigerante Coca-Cola Lata 350ml", description: "Lata 350ml", price: 7.0, category: "BEBIDA", order: 9 },
  { name: "Refrigerante Guaraná Fruki Lata 350ml", description: "Lata 350ml", price: 7.0, category: "BEBIDA", order: 10 },
  { name: "Refrigerante Guaraná Fruki Light Lata 350ml", description: "Lata 350ml", price: 7.0, category: "BEBIDA", order: 11 },
  { name: "Água com Gás", description: "", price: 4.0, category: "BEBIDA", order: 12 },
];

module.exports = { pizzaSizes, borders, flavors, products };
