-- AddColumn to admins
ALTER TABLE "admins" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'ADMIN';
ALTER TABLE "admins" ADD COLUMN "totpSecret" TEXT;
ALTER TABLE "admins" ADD COLUMN "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "admins" ADD COLUMN "backupCodes" TEXT;
ALTER TABLE "admins" ADD COLUMN "lastLoginAt" TIMESTAMP(3);
ALTER TABLE "admins" ADD COLUMN "lastLoginIp" TEXT;
ALTER TABLE "admins" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
